-- Replace unstable numeric psychube_id (sort-position-based) with name-based stable key.
-- IDs were assigned as idx+1 after alphabetical sort; new psychubes shifted all IDs downstream.
ALTER TABLE r1999_tracked_arcanists ADD COLUMN psychube_name TEXT;

UPDATE r1999_tracked_arcanists
SET psychube_name = CASE psychube_id::integer
  WHEN 1 THEN 'A Tingle of a Thought'
  WHEN 2 THEN 'Across the Acheron'
  WHEN 3 THEN 'Addio Coda'
  WHEN 4 THEN 'An Epic''s End'
  WHEN 5 THEN 'And the Maid Says'
  WHEN 6 THEN 'Another Story'
  WHEN 7 THEN 'Approaching Rain'
  WHEN 8 THEN 'As the Bell Tolls'
  WHEN 9 THEN 'Aurora After Winter'
  WHEN 10 THEN 'Balance, Please'
  WHEN 11 THEN 'Beyond Wonderland'
  WHEN 12 THEN 'Bitter March of the Living'
  WHEN 13 THEN 'Blasphemer of Night'
  WHEN 14 THEN 'Brave New World'
  WHEN 15 THEN 'Buds Yet to Bloom'
  WHEN 16 THEN 'Cracks in the Shell'
  WHEN 17 THEN 'Dawn Is Coming'
  WHEN 18 THEN 'EHF Polarization'
  WHEN 19 THEN 'Embrace the Past'
  WHEN 20 THEN 'Family Mentor'
  WHEN 21 THEN 'For Rehabilitation'
  WHEN 22 THEN 'From the Depths'
  WHEN 23 THEN 'Gluttony'
  WHEN 24 THEN 'Her Second Life'
  WHEN 25 THEN 'Her Willful Leap'
  WHEN 26 THEN 'His Bounden Duty'
  WHEN 27 THEN 'Homecoming Lament'
  WHEN 28 THEN 'Hopscotch'
  WHEN 29 THEN 'Into the Gentle Current'
  WHEN 30 THEN 'Knock on the Door'
  WHEN 31 THEN 'Long Night Talk'
  WHEN 32 THEN 'Luxurious Leisure'
  WHEN 33 THEN 'Mental Cage'
  WHEN 34 THEN 'Never-Ending Q&A'
  WHEN 35 THEN 'Offbeat Strides'
  WHEN 36 THEN 'On the Hand of Time'
  WHEN 37 THEN 'Outside the City'
  WHEN 38 THEN 'Ready on Call'
  WHEN 39 THEN 'Rehearsal of Dreams'
  WHEN 40 THEN 'Same Old Story'
  WHEN 41 THEN 'Shadows in the Subconscious'
  WHEN 42 THEN 'Silent and Adoring'
  WHEN 43 THEN 'Singleness of Heart'
  WHEN 44 THEN 'Starlight Wellspring'
  WHEN 45 THEN 'Steps Forward'
  WHEN 46 THEN 'Stray Off the Path'
  WHEN 47 THEN 'Template:Psychube'
  WHEN 48 THEN 'That Inquisitive Dear'
  WHEN 49 THEN 'The Carat of a Heart'
  WHEN 50 THEN 'The Fighter''s Best Wishes'
  WHEN 51 THEN 'The Final Roll'
  WHEN 52 THEN 'The Third Commitment'
  WHEN 53 THEN 'The Thousandfold Fate'
  WHEN 54 THEN 'The Unbearable Lightness'
  WHEN 55 THEN 'The Wandering Improviser'
  WHEN 56 THEN 'Thunderous Applause'
  WHEN 57 THEN 'Tiny Wish'
  WHEN 58 THEN 'Transcendent Love'
  WHEN 59 THEN 'A Free Heart'
  WHEN 60 THEN 'A Satisfied Eater'
  WHEN 61 THEN 'An Afternoon Nap'
  WHEN 62 THEN 'Belt It Out'
  WHEN 63 THEN 'Beyond the Gears'
  WHEN 64 THEN 'Decode'
  WHEN 65 THEN 'Dust on the Roadside'
  WHEN 66 THEN 'Enlighten IV'
  WHEN 67 THEN 'Faded Epitaphs'
  WHEN 68 THEN 'Falling for a Sweet Phenomenon'
  WHEN 69 THEN 'Going Along Alone'
  WHEN 70 THEN 'Greed'
  WHEN 71 THEN 'Her Bright Future'
  WHEN 72 THEN 'Her Mournful Face'
  WHEN 73 THEN 'HF Polarization'
  WHEN 74 THEN 'His Tail'
  WHEN 75 THEN 'In the Shadow'
  WHEN 76 THEN 'In Their Figures'
  WHEN 77 THEN 'Laughter and Laughter'
  WHEN 78 THEN 'Let''s Set Sail'
  WHEN 79 THEN 'Melodies Old and New'
  WHEN 80 THEN 'Night After Night'
  WHEN 81 THEN 'Off the Scene'
  WHEN 82 THEN 'One with the Flow'
  WHEN 83 THEN 'Parting''s Quiet Lament'
  WHEN 84 THEN 'Remaining Absurdity'
  WHEN 85 THEN 'Silent Gaze'
  WHEN 86 THEN 'Spinning Yarns'
  WHEN 87 THEN 'Substitutes and Simulacra'
  WHEN 88 THEN 'Take the Hard Journey'
  WHEN 89 THEN 'Tea Break'
  WHEN 90 THEN 'The Footloose'
  WHEN 91 THEN 'The Loner'
  WHEN 92 THEN 'The Severed and the Rest'
  WHEN 93 THEN 'Tomorrow Also'
  WHEN 94 THEN 'Yearning Desire'
  WHEN 95 THEN 'You Deserve It'
  WHEN 96 THEN 'Your Friendly Exorcist'
  WHEN 97 THEN 'Bow'
  WHEN 98 THEN 'Covet'
  WHEN 99 THEN 'Enlighten III'
  WHEN 100 THEN 'Meek'
  WHEN 101 THEN 'MF Polarization'
  WHEN 102 THEN 'Navigating'
  WHEN 103 THEN 'Venomous'
  WHEN 104 THEN 'Cheering'
  WHEN 105 THEN 'Enlighten II'
  WHEN 106 THEN 'Fatuous'
  WHEN 107 THEN 'Flourishing'
  WHEN 108 THEN 'LF Polarization'
  WHEN 109 THEN 'Loss'
  WHEN 110 THEN 'Numb'
  WHEN 111 THEN 'Slighted'
  ELSE NULL
END
WHERE psychube_id IS NOT NULL;

ALTER TABLE r1999_tracked_arcanists DROP COLUMN psychube_id;
